[toolchain]
anchor_version = "0.30.0"
rust_version = "1.90.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
registry = "poiRegistry1111111111111111111111111"
staking = "poiStaking1111111111111111111111111"
consensus = "poiConsensus111111111111111111111111"
emissions = "poiEmissions111111111111111111111111"
hive = "poiHive1111111111111111111111111111111"

[registry]
cluster = "Localnet"
address = "poiRegistry1111111111111111111111111"

[staking]
cluster = "Localnet"
address = "poiStaking1111111111111111111111111"

[consensus]
cluster = "Localnet"
address = "poiConsensus111111111111111111111111"

[emissions]
cluster = "Localnet"
address = "poiEmissions111111111111111111111111"

[hive]
cluster = "Localnet"
address = "poiHive1111111111111111111111111111111"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

